# =======================
# DATAGEN
# =======================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datagen-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datagen
  template:
    metadata:
      labels:
        app: datagen
    spec:
      containers:
      - name: datagen
        image: grpc-pipeline:k8s
        imagePullPolicy: IfNotPresent
        command: ["python", "datagen_server.py"]
        ports:
        - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: datagen
spec:
  selector:
    app: datagen
  ports:
    - port: 50051
      targetPort: 50051
  type: ClusterIP

# =======================
# PREPROCESS
# =======================
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: preprocess-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: preprocess
  template:
    metadata:
      labels:
        app: preprocess
    spec:
      containers:
      - name: preprocess
        image: grpc-pipeline:k8s
        imagePullPolicy: IfNotPresent
        command: ["python", "preprocess_server.py"]
        ports:
        - containerPort: 50052
---
apiVersion: v1
kind: Service
metadata:
  name: preprocess
spec:
  selector:
    app: preprocess
  ports:
    - port: 50052
      targetPort: 50052
  type: ClusterIP

# =======================
# FEATURE
# =======================
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feature
  template:
    metadata:
      labels:
        app: feature
    spec:
      containers:
      - name: feature
        image: grpc-pipeline:k8s
        imagePullPolicy: IfNotPresent
        command: ["python", "feature_server.py"]
        ports:
        - containerPort: 50053
---
apiVersion: v1
kind: Service
metadata:
  name: feature
spec:
  selector:
    app: feature
  ports:
    - port: 50053
      targetPort: 50053
  type: ClusterIP

# =======================
# ANALYSIS
# =======================
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analysis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analysis
  template:
    metadata:
      labels:
        app: analysis
    spec:
      containers:
      - name: analysis
        image: grpc-pipeline:k8s
        imagePullPolicy: IfNotPresent
        command: ["python", "analysis_server.py"]
        ports:
        - containerPort: 50054
---
apiVersion: v1
kind: Service
metadata:
  name: analysis
spec:
  selector:
    app: analysis
  ports:
    - port: 50054
      targetPort: 50054
  type: ClusterIP

# =======================
# MASTER
# =======================
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
      - name: master
        image: grpc-pipeline:k8s-final
        imagePullPolicy: IfNotPresent
        command: ["python", "master_server.py"]
        ports:
        - containerPort: 50055
---
apiVersion: v1
kind: Service
metadata:
  name: master
spec:
  selector:
    app: master
  ports:
    - port: 50055
      targetPort: 50055
  type: NodePort
