# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pipeline.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'pipeline.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0epipeline.proto\x12\x08pipeline\"\x1b\n\x0b\x44\x61taRequest\x12\x0c\n\x04size\x18\x01 \x01(\x05\"8\n\x0c\x44\x61taResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x01\x12\x0c\n\x04rows\x18\x02 \x01(\x05\x12\x0c\n\x04\x63ols\x18\x03 \x01(\x05\"#\n\x0f\x46\x65\x61tureResponse\x12\x10\n\x08\x66\x65\x61tures\x18\x01 \x03(\x01\"U\n\x10\x41nalysisResponse\x12\x13\n\x0b\x63orrelation\x18\x01 \x01(\x01\x12\x14\n\x0c\x61vg_distance\x18\x02 \x01(\x01\x12\x16\n\x0e\x63luster_result\x18\x03 \x01(\t\"$\n\x0fPipelineRequest\x12\x11\n\tdata_size\x18\x01 \x01(\x05\"7\n\x10PipelineResponse\x12\x12\n\ntotal_time\x18\x01 \x01(\x01\x12\x0f\n\x07summary\x18\x02 \x01(\t2O\n\x0e\x44\x61taGenService\x12=\n\x0cGenerateData\x12\x15.pipeline.DataRequest\x1a\x16.pipeline.DataResponse2P\n\x11PreprocessService\x12;\n\tCleanData\x12\x16.pipeline.DataResponse\x1a\x16.pipeline.DataResponse2V\n\x0e\x46\x65\x61tureService\x12\x44\n\x0f\x45xtractFeatures\x12\x16.pipeline.DataResponse\x1a\x19.pipeline.FeatureResponse2W\n\x0f\x41nalysisService\x12\x44\n\x0b\x41nalyzeData\x12\x19.pipeline.FeatureResponse\x1a\x1a.pipeline.AnalysisResponse2U\n\rMasterService\x12\x44\n\x0bRunPipeline\x12\x19.pipeline.PipelineRequest\x1a\x1a.pipeline.PipelineResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pipeline_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATAREQUEST']._serialized_start=28
  _globals['_DATAREQUEST']._serialized_end=55
  _globals['_DATARESPONSE']._serialized_start=57
  _globals['_DATARESPONSE']._serialized_end=113
  _globals['_FEATURERESPONSE']._serialized_start=115
  _globals['_FEATURERESPONSE']._serialized_end=150
  _globals['_ANALYSISRESPONSE']._serialized_start=152
  _globals['_ANALYSISRESPONSE']._serialized_end=237
  _globals['_PIPELINEREQUEST']._serialized_start=239
  _globals['_PIPELINEREQUEST']._serialized_end=275
  _globals['_PIPELINERESPONSE']._serialized_start=277
  _globals['_PIPELINERESPONSE']._serialized_end=332
  _globals['_DATAGENSERVICE']._serialized_start=334
  _globals['_DATAGENSERVICE']._serialized_end=413
  _globals['_PREPROCESSSERVICE']._serialized_start=415
  _globals['_PREPROCESSSERVICE']._serialized_end=495
  _globals['_FEATURESERVICE']._serialized_start=497
  _globals['_FEATURESERVICE']._serialized_end=583
  _globals['_ANALYSISSERVICE']._serialized_start=585
  _globals['_ANALYSISSERVICE']._serialized_end=672
  _globals['_MASTERSERVICE']._serialized_start=674
  _globals['_MASTERSERVICE']._serialized_end=759
# @@protoc_insertion_point(module_scope)
