# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import pipeline_pb2 as pipeline__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in pipeline_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DataGenServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateData = channel.unary_unary(
                '/pipeline.DataGenService/GenerateData',
                request_serializer=pipeline__pb2.DataRequest.SerializeToString,
                response_deserializer=pipeline__pb2.DataResponse.FromString,
                _registered_method=True)


class DataGenServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataGenServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateData': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateData,
                    request_deserializer=pipeline__pb2.DataRequest.FromString,
                    response_serializer=pipeline__pb2.DataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pipeline.DataGenService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pipeline.DataGenService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataGenService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pipeline.DataGenService/GenerateData',
            pipeline__pb2.DataRequest.SerializeToString,
            pipeline__pb2.DataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PreprocessServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CleanData = channel.unary_unary(
                '/pipeline.PreprocessService/CleanData',
                request_serializer=pipeline__pb2.DataResponse.SerializeToString,
                response_deserializer=pipeline__pb2.DataResponse.FromString,
                _registered_method=True)


class PreprocessServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CleanData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PreprocessServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CleanData': grpc.unary_unary_rpc_method_handler(
                    servicer.CleanData,
                    request_deserializer=pipeline__pb2.DataResponse.FromString,
                    response_serializer=pipeline__pb2.DataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pipeline.PreprocessService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pipeline.PreprocessService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PreprocessService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CleanData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pipeline.PreprocessService/CleanData',
            pipeline__pb2.DataResponse.SerializeToString,
            pipeline__pb2.DataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class FeatureServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExtractFeatures = channel.unary_unary(
                '/pipeline.FeatureService/ExtractFeatures',
                request_serializer=pipeline__pb2.DataResponse.SerializeToString,
                response_deserializer=pipeline__pb2.FeatureResponse.FromString,
                _registered_method=True)


class FeatureServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExtractFeatures(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FeatureServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExtractFeatures': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractFeatures,
                    request_deserializer=pipeline__pb2.DataResponse.FromString,
                    response_serializer=pipeline__pb2.FeatureResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pipeline.FeatureService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pipeline.FeatureService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FeatureService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExtractFeatures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pipeline.FeatureService/ExtractFeatures',
            pipeline__pb2.DataResponse.SerializeToString,
            pipeline__pb2.FeatureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AnalysisServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeData = channel.unary_unary(
                '/pipeline.AnalysisService/AnalyzeData',
                request_serializer=pipeline__pb2.FeatureResponse.SerializeToString,
                response_deserializer=pipeline__pb2.AnalysisResponse.FromString,
                _registered_method=True)


class AnalysisServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AnalyzeData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalysisServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeData': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeData,
                    request_deserializer=pipeline__pb2.FeatureResponse.FromString,
                    response_serializer=pipeline__pb2.AnalysisResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pipeline.AnalysisService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pipeline.AnalysisService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnalysisService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnalyzeData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pipeline.AnalysisService/AnalyzeData',
            pipeline__pb2.FeatureResponse.SerializeToString,
            pipeline__pb2.AnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MasterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunPipeline = channel.unary_unary(
                '/pipeline.MasterService/RunPipeline',
                request_serializer=pipeline__pb2.PipelineRequest.SerializeToString,
                response_deserializer=pipeline__pb2.PipelineResponse.FromString,
                _registered_method=True)


class MasterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunPipeline(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MasterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunPipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.RunPipeline,
                    request_deserializer=pipeline__pb2.PipelineRequest.FromString,
                    response_serializer=pipeline__pb2.PipelineResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pipeline.MasterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pipeline.MasterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MasterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunPipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pipeline.MasterService/RunPipeline',
            pipeline__pb2.PipelineRequest.SerializeToString,
            pipeline__pb2.PipelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
